version: '3.8'

services:
    db:
        image: mongo
        container_name: mongo_c
        # démarrer le conteneur en cas de redémarrage du serveurs
        restart: always
        volumes:
            # pour initialiser la db
            # docker-entrypoint-initdb.d existe déjà dans le conteneur mongo
            # ro : read only
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            # pour la persitence des données
            #- ./mongo-volume:/data/db
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: "username"
            ME_CONFIG_BASICAUTH_PASSWORD: "password" 
        ports:
          - '27018:27018' 
    app:
        image: myapp_i
        container_name: myapp_c
        restart: always
        ports:
            - 8080:80
        depends_on:
            - db