version: '3.8'

services:
    db:
        image: mongo-express:latest
        container_name: mongo_c
        restart: always
        volumes:
            # pour initialiser la db
            # docker-entrypoint-initdb.d existe déjà dans le conteneur mongo
            # ro : read only
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            # pour la persitence des données
            - ./mongo-volume:/data/db
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: "user"
            ME_CONFIG_BASICAUTH_PASSWORD: "sebastien" 
        ports:
          # exposer les ports de 27017 à 27019
          - '27017-27019:27017-27019' 
    app:
        image: myapp
        container_name: myapp_c
        restart: always
        volumes:
            - ./app:/var/www/html
        ports:
            - 8080:80
        depends_on:
            - db

volumes:
    db-volume: