version: '3.8'

services:
    db:
        image: mysql
        container_name: mysql_c
        volumes:
            - ./db/:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: db2
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3306:3306'
        expose:
            - 3306
    app:
        build: .
        image: myapp_i
        container_name: myapp_c
        ports:
            - 3000:3000
        depends_on:
            - db
 