version: '2'

services:
  mysql:
    image: mysql
    container_name: mysql_c
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db2
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - 3306:3306
  app:
    build: .
    image: myapp_i
    ports:
      - 80:80
    depends_on:
      - mysql