version: '3.8'

services:
    db:
        image: mysql/mysql-server:5.7
        ports:
        - 3306:3306
        environment:
        - MYSQL_ROOT_PASSWORD="rootpass"
        - MYSQL_USER="user"
        - MYSQL_PASSWORD="password"
        - MYSQL_DATABASE="mysql"
    superapachephp:
        build: ./
        ports:
        - "8010:80"
        links:
        - "db:db"
        working_dir: "/home/docker"